version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - smashcode_network
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_CLAVE:-root}
      MYSQL_DATABASE: smash_code
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - smashcode_network
volumes:
  db_data:
networks:
  smashcode_network:
    driver: bridge